site_name: MagIC High Performance Computing Cluster

nav:
  - Home: index.md
  - Hardware: hardware.md
  - Software: software.md
  - Database: database.md
  - Service: service.md
  - About: about.md

theme: material

markdown_extensions:
  - attr_list
